### ISSUE TITLE
Licence contract's load() function will execute `transferFrom` on an arbitrary contract

### ISSUE THREAD

**Issue by draganm** [tokencard/contracts#546] opened 2020-04-01 11:28 UTC
Licence contract is not checking if the assed that is being loaded is supported and will execute `transferFrom` on any contract address passed as argument.
We should introduce a check by consulting token whitelist before transferring ERC20

**Comment by i-stam** [comment] 2020-04-09 16:42
duplicate of #547

**Closed by i-stam** 2020-04-09 16:42 UTC
Labels: duplicate
